name: Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Ejecuta la animaci√≥n todos los d√≠as a la medianoche
  workflow_dispatch: # Permite ejecutarlo manualmente desde Actions

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3
        
      - name: Generar Snake üêç
        uses: Platane/snk@v3
        with:
          github_user_name: ChillRelaxing # Tu nombre de usuario
          svg_out_path: dist/snake.svg

      - name: Subir Snake
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
